import { NextRequest, NextResponse } from 'next/server';

// Cache this response for 24 hours at the CDN/Vercel edge level
export const dynamic = 'force-dynamic';
export const revalidate = 86400; // 24 hours

// R2 CDN base URL — set this env var once you upload assets to R2
const R2_BASE_URL = process.env.NEXT_PUBLIC_R2_BASE_URL || '';

// ─── Helpers ─────────────────────────────────────────────────────────────────

function isImageFile(name: string): boolean {
  const ext = name.split('.').pop()?.toLowerCase() ?? '';
  return ['png', 'jpg', 'jpeg', 'webp'].includes(ext);
}

function naturalSort(a: string, b: string): number {
  return a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' });
}

// ─── R2 Mode (Vercel / production) ───────────────────────────────────────────
// When R2_BASE_URL is set, we don't read the local filesystem at all.
// Instead we return frame URLs pointing to the R2 CDN.
// The R2 bucket must mirror the structure: /extracted/{folder}/{partN}/{frame}.png

async function getFramesFromR2(folder: string) {
  // We fetch the manifest JSON from R2 that lists all frame filenames per part.
  // This manifest is generated by the upload script (scripts/upload-to-r2.sh).
  const manifestUrl = `${R2_BASE_URL}/extracted/${encodeURIComponent(folder)}/manifest.json`;

  try {
    const res = await fetch(manifestUrl, {
      next: { revalidate: 86400 }, // Cache manifest for 24h in Next.js data cache
    });

    if (!res.ok) throw new Error(`Manifest fetch failed: ${res.status}`);

    const manifest: Record<string, string[]> = await res.json();

    const parts = Object.entries(manifest)
      .sort(([a], [b]) => naturalSort(a, b))
      .map(([partName, files]) => ({
        partName,
        frames: files.map(
          (f) => `${R2_BASE_URL}/extracted/${encodeURIComponent(folder)}/${partName}/${f}`
        ),
      }));

    return NextResponse.json({ parts, source: 'r2' }, {
      headers: {
        'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=604800',
      },
    });
  } catch {
    return NextResponse.json(
      { error: 'Manifest not found on R2. Run the upload script first.', manifestUrl },
      { status: 404 }
    );
  }
}

// ─── Local Filesystem Mode (dev / self-hosted) ────────────────────────────────
async function getFramesFromFilesystem(folder: string) {
  // Dynamic import so this code is tree-shaken on Vercel (no `fs` on edge)
  const fs = await import('fs');
  const path = await import('path');

  const EXTRACTED_DIR = path.resolve(process.cwd(), '../extracted');
  const targetDir = path.join(EXTRACTED_DIR, folder);

  if (!fs.existsSync(targetDir)) {
    return NextResponse.json({ error: 'Animation directory not found' }, { status: 404 });
  }

  const items = fs.readdirSync(targetDir);
  const partDirs = items
    .filter(
      (item: string) =>
        fs.statSync(path.join(targetDir, item)).isDirectory() && item.startsWith('part')
    )
    .sort(naturalSort);

  if (partDirs.length === 0) {
    return NextResponse.json({ error: 'No animation parts found' }, { status: 404 });
  }

  const partsData = partDirs.map((partDir: string) => {
    const partPath = path.join(targetDir, partDir);
    const fileNames = fs.readdirSync(partPath).filter(isImageFile).sort(naturalSort);
    const frames = fileNames.map(
      (fileName: string) =>
        `/extracted/${encodeURIComponent(folder)}/${partDir}/${fileName}`
    );
    return { partName: partDir, frames };
  });

  return NextResponse.json({ parts: partsData, source: 'filesystem' }, {
    headers: {
      'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
    },
  });
}

// ─── Main Handler ─────────────────────────────────────────────────────────────
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const folder = searchParams.get('folder');

    if (!folder) {
      return NextResponse.json({ error: 'folder param is required' }, { status: 400 });
    }

    // Use R2 in production when the env var is set, fallback to filesystem in dev
    if (R2_BASE_URL) {
      return await getFramesFromR2(folder);
    } else {
      return await getFramesFromFilesystem(folder);
    }
  } catch (error) {
    const err = error as Error;
    console.error('Error in /api/frames:', err);
    return NextResponse.json(
      { error: 'Failed to retrieve frames', details: err.message },
      { status: 500 }
    );
  }
}
